stages:
  - lint
  - test
  - build

# For now pipelines on run on the frontend code, these will need to be
# reassigned on a per-job basis when the backend is added to pipelines.

"FE Linting":
  image: node:10
  stage: lint
  script:
    - cd mellophone/frontend
    - yarn
    - yarn lint

"FE Testing":
  image: node:10
  stage: test
  script:
    - cd mellophone/frontend
    - yarn
    - yarn test

"FE Build":
  image: node:10
  stage: build
  script:
    - cd mellophone/frontend
    - yarn
    - yarn build

"BE Linting":
  image: python:3
  stage: lint
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run lint
