stages:
  - build
  - test
  - lint
  - deploy

variables:
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIPENV_DONT_LOAD_ENV: "true" # provided by gitlab ci
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: "postgres"

cache:
  paths:
    - .cache
    - mellophone/frontend/node_modules
    - mellophone/frontend/build
    - .yarn

"FE Linting":
  image: node:10-alpine
  stage: lint
  script:
    - cd mellophone/frontend
    - yarn
    - yarn lint

"FE Testing":
  image: node:10-alpine
  stage: test
  script:
    - cd mellophone/frontend
    - yarn
    - yarn test

"FE Build":
  image: node:10-alpine
  stage: build
  script:
    - cd mellophone/frontend
    - yarn
    - yarn build

"BE Linting":
  image: nchlswhttkr/mellophone
  stage: lint
  script:
    - pip3 install pipenv
    - pipenv sync --dev
    - pipenv run lint

"BE Testing":
  image: nchlswhttkr/mellophone
  stage: test
  services:
    - postgres:11
  script:
    - pipenv sync
    - pipenv run db-migrate
    - pipenv run test-unit
