stages:
  - build
  - test
  - lint
  - deploy

variables:
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"

cache:
  paths:
    # mellophone/frontend/build is not cached, it should be built with each job that needs it
    - .cache
    - mellophone/frontend/node_modules
    - .yarn

"FE Linting":
  image: node:10
  stage: lint
  script:
    - cd mellophone/frontend
    - yarn
    - yarn lint

"FE Testing":
  image: node:10
  stage: test
  script:
    - cd mellophone/frontend
    - yarn
    - yarn test

"FE Build":
  image: node:10
  stage: build
  script:
    - cd mellophone/frontend
    - yarn
    - yarn build

"BE Linting":
  image: python:3
  stage: lint
  script:
    - pip install pipenv
    - pipenv sync --dev
    - pipenv run lint

"BE Testing":
  image: python:3
  stage: test
  services:
    - postgres:10
  script:
    - pip install pipenv
    - pipenv sync
    - pipenv run db-init
    - pipenv run db-start
    - pipenv run test-unit
    - pipenv run db-stop
