version: "3.7"

services:
  dev:
    image: "nchlswhttkr/mellophone"
    working_dir: "/home/conductor/dev"
    environment:
      - "PIPENV_VENV_IN_PROJECT=true"
    volumes:
      - ".:/home/conductor/dev"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    command: "pipenv run server"
  db:
    image: "postgres:10"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mellophone"
    ports:
      - "5432:5432"
