version: "3.7"

services:
  dev:
    image: "registry.gitlab.com/nchlswhttkr/mellophone:master"
    working_dir: "/home/mellophone/dev"
    environment:
      # Ensures all 'dev' containers use the same dependencies
      - "WORKON_HOME=/home/mellophone/dev/docker/dev/.venv"
    volumes:
      - ".:/home/mellophone/dev"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    command: "pipenv run server"
  db:
    image: "postgres:10"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mellophone"
    ports:
      - "5432:5432"
