# Generated by Django 2.2.4 on 2019-08-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190401_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='MeetingAttendee',
        ),
    ]
