# Generated by Django 2.2.4 on 2019-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0005_auto_20190813_0421")]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="venue",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        )
    ]
